'use strict';
const $=id=>document.getElementById(id);
const CODE_HASH='49af5997d4acc06604f42debd0de05ed251efa294180ef06683555f79fd8b6bc';
const PAGE_SIZE=6,MAX_FILE=10*1024*1024;
let tracker=null,tab='all',mode='table',query='',editing=null,marking=null,deleting=null;
const pages={},groups=[['applications','Applications'],['ready','Ready'],['leads','Leads'],['interviews','Interviews'],['offers','Offers'],['unsuccessful','Unsuccessful'],['attention','Needs attention']];
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n};
const fmt=v=>{if(!v)return 'Not recorded';const d=new Date(v);return Number.isNaN(d.valueOf())?String(v):new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Sydney',day:'numeric',month:'short',year:'numeric'}).format(d)};
const empty=()=>({applications:[],leads:[],manual_entries:[],record_visibility:[],deleted_keys:[],updated_at:new Date().toISOString()});
function message(s,warn=false){$('status').textContent=s;$('status').classList.toggle('warning',warn)}
function validUrl(u){try{const v=new URL(u);return ['https:','http:','mailto:'].includes(v.protocol)?v.href:null}catch{return null}}
function link(label,url){const a=el('a',label),safe=validUrl(url);if(!safe)return el('span',label);a.href=safe;a.target='_blank';a.rel='noopener noreferrer';return a}
function bytesToBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function base64ToBytes(s){const raw=atob(s.replace(/\s/g,''));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function sha256(s){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(h),v=>v.toString(16).padStart(2,'0')).join('')}
function openStore(){return new Promise((resolve,reject)=>{const req=indexedDB.open('marc-job-tracker',1);req.onupgradeneeded=()=>req.result.createObjectStore('records');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function readLocal(){const db=await openStore();return new Promise((resolve,reject)=>{const tx=db.transaction('records'),req=tx.objectStore('records').get('current');req.onsuccess=()=>{db.close();resolve(req.result||null)};req.onerror=()=>{db.close();reject(req.error)}})}
async function writeLocal(value){const db=await openStore();return new Promise((resolve,reject)=>{const tx=db.transaction('records','readwrite');tx.objectStore('records').put(value,'current');tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
function mergeSnapshot(base,local){if(!local)return base;for(const k of ['applications','leads','manual_entries']){const current=new Map((local[k]||[]).map(r=>[r.key||r.id,r]));base[k]=base[k].map(r=>current.get(r.key||r.id)||r);const known=new Set(base[k].map(r=>r.key||r.id));for(const r of local[k]||[])if(!known.has(r.key||r.id))base[k].push(r)}const visibility=new Map((base.record_visibility||[]).map(r=>[r.record_key,r]));for(const r of local.record_visibility||[])visibility.set(r.record_key,r);base.record_visibility=[...visibility.values()];base.updated_at=local.updated_at||base.updated_at;return base}
async function load(){message('Loading records…');const response=await fetch('./data.json',{cache:'no-store'});if(!response.ok)throw Error('The published tracker data is unavailable.');const published=await response.json();validate(published);const saved=await readLocal();tracker=mergeSnapshot(published,saved);validate(tracker);render();message(saved?'Loaded your browser edits. Export JSON to share them.':'Published tracker loaded. Edits stay in this browser until exported.')}
function validate(d){if(!d||!Array.isArray(d.applications)||!Array.isArray(d.leads)||!Array.isArray(d.manual_entries)||!Array.isArray(d.record_visibility))throw Error('The private tracker JSON has an invalid format.')}
async function save(){tracker.updated_at=new Date().toISOString();await writeLocal(tracker);render()}
function allRows(){const overrides=new Map(tracker.record_visibility.map(v=>[v.record_key,v]));const manual=tracker.manual_entries||[];const appliedKeys=new Set(manual.map(r=>r.origin_key).filter(Boolean));const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');const urlKey=s=>{try{const u=new URL(s);return u.hostname.toLowerCase()+u.pathname.replace(/\/$/,'').toLowerCase()}catch{return ''}};const urls=new Set(manual.map(r=>urlKey(r.job_url)).filter(Boolean)),names=new Set(manual.map(r=>norm(r.company)+'|'+norm(r.role)));const automatic=[...tracker.applications,...tracker.leads].filter(r=>overrides.get(r.key)?.deleted||(!appliedKeys.has(r.key)&&!(r.job_url&&urls.has(urlKey(r.job_url)))&&!names.has(norm(r.company)+'|'+norm(r.role))));const rows=automatic.concat(manual.map(r=>({...r,key:r.key||'manual:'+r.id,manual_entry_id:r.id})));const active=[],bin=[];for(const r of rows){const vis=overrides.get(r.key);const record={...r,deleted:!!vis?.deleted,visibility_version:vis?.version||0};if(record.deleted)bin.push(record);else if(!/^EXPIRED$|^SKIPPED_EXPIRED$|^SKIPPED_CLOSED$|^VACANCY_REMOVED$/.test(record.status||''))active.push(record)}return {active,bin}}
function group(r){const s=r.status||'';if(s==='INTERVIEW')return 'interviews';if(s==='OFFER')return 'offers';if(s==='REJECTED')return 'unsuccessful';if(['SENT','MANUAL_APPLIED','DELIVERY_FAILED'].includes(s))return 'applications';if(/READY|PREPARED|APPROVED/.test(s))return 'ready';if(/BLOCKED|FAILED|UNCERTAIN|SENDING/.test(s))return 'attention';return 'leads'}
function label(r){return ({SENT:'Email sent',MANUAL_APPLIED:'Applied · reported',INTERVIEW:'Interview',OFFER:'Offer',REJECTED:'Unsuccessful',LEAD:'Lead',READY_FOR_JEREMIE:'Jeremie · apply',DELIVERY_FAILED:'Delivery failed',SEND_UNCERTAIN:'Send uncertain'})[r.status]||String(r.status||'Lead').replaceAll('_',' ').toLowerCase()}
function pill(r){const g=group(r);return el('span',label(r),'pill '+({applications:'applied',ready:'ready',interviews:'interview',attention:'attention'}[g]||''))}
function match(r){const v=r.match_score?.percent;if(typeof v!=='number')return null;const box=el('div',undefined,'match'+(v<80?' medium':'')),bar=el('div',undefined,'match-track'),fill=el('div',undefined,'match-fill');fill.style.width=Math.max(0,Math.min(100,v))+'%';bar.append(fill);box.append(el('span',v+'% fit'),bar);box.title='Judgement-based résumé or company-scope fit, not interview probability';return box}
function filtered(){const {active,bin}=allRows();const list=tab==='bin'?bin:tab==='applied'?active.filter(r=>group(r)==='applications'):active;const q=query.trim().toLowerCase();return q?list.filter(r=>[r.company,r.role,r.location,r.status].some(v=>String(v||'').toLowerCase().includes(q))):list}
function render(){if(!tracker)return;const {active}=allRows();for(const [id,fn] of [['applications',r=>group(r)==='applications'],['ready',r=>group(r)==='ready'],['leads',r=>group(r)==='leads'],['interviews',r=>group(r)==='interviews']])$('count-'+id).textContent=active.filter(fn).length;$('updated').textContent='Last saved '+fmt(tracker.updated_at);$('page-title').textContent=tab==='bin'?'Bin':tab==='applied'?'Applications':'Applications and leads';$('section-name').textContent=tab==='bin'?'Bin':tab==='applied'?'Applications':'Overview';for(const id of ['all','applied','bin'])$('nav-'+id).classList.toggle('active',id===tab);$('table-mode').setAttribute('aria-pressed',String(mode==='table'));$('scroll-mode').setAttribute('aria-pressed',String(mode==='scroll'));const root=$('records');root.replaceChildren();const list=filtered();if(tab==='bin'){root.append(renderCards(list,true));return}if(mode==='scroll'){root.append(renderCards(list,false));return}for(const [key,title] of groups){const subset=list.filter(r=>group(r)===key);if(!subset.length&&!['applications','ready','leads'].includes(key))continue;const section=el('section',undefined,'group'),h=el('h2',undefined,'group-title');h.append(title,el('span',subset.length));section.append(h);const wrap=el('div',undefined,'table-wrap');wrap.tabIndex=0;const table=el('table'),thead=el('thead'),thr=el('tr');for(const name of ['Company / role','Location','Contact','Status','Activity','Actions'])thr.append(el('th',name));thead.append(thr);table.append(thead);const body=el('tbody');const count=Math.max(1,Math.ceil(subset.length/PAGE_SIZE));pages[key]=Math.min(pages[key]||1,count);for(const r of subset.slice((pages[key]-1)*PAGE_SIZE,pages[key]*PAGE_SIZE))body.append(row(r));if(!subset.length){const tr=el('tr'),td=el('td','No '+title.toLowerCase()+' yet.','empty');td.colSpan=6;tr.append(td);body.append(tr)}table.append(body);wrap.append(table);section.append(wrap);if(count>1){const p=el('div',undefined,'pagination'),prev=el('button','Previous'),next=el('button','Next');prev.disabled=pages[key]===1;next.disabled=pages[key]===count;prev.onclick=()=>{pages[key]--;render()};next.onclick=()=>{pages[key]++;render()};p.append(prev,el('span',pages[key]+' / '+count),next);section.append(p)}root.append(section)}}
function actions(r,bin=false){const box=el('div',undefined,'row-actions'),details=el('button','Details');details.onclick=()=>openDetail(r);box.append(details);if(bin){const restore=el('button','Restore');restore.onclick=()=>setDeleted(r,false);box.append(restore)}else{if(['ready','leads'].includes(group(r))){const apply=el('button','Applied','applied-action');apply.onclick=()=>openEditor(r,true);box.append(apply)}const edit=el('button','Edit');edit.onclick=()=>openEditor(r,false);box.append(edit);const del=el('button','Delete');del.onclick=()=>{deleting=r;$('confirm-name').textContent=r.company+' — '+r.role;$('confirm').showModal()};box.append(del)}return box}
function row(r){const tr=el('tr'),co=el('td');co.append(el('strong',r.company||'Unknown'),el('small',r.role||'Role not recorded','role'));const m=match(r);if(m)co.append(m);tr.append(co,el('td',r.location||'Not recorded'),el('td',r.recipient_name||r.contact_email||'Contact needed'));const status=el('td');status.append(pill(r));tr.append(status,el('td',fmt(r.sent_at||r.checked_at||r.applied_date||r.updated_at)));const action=el('td');action.append(actions(r));tr.append(action);return tr}
function renderCards(list,bin){const box=el('div',undefined,'cards');if(!list.length)box.append(el('p',bin?'The Bin is empty.':'No matching records.','empty'));for(const r of list){const c=el('article',undefined,'card'),head=el('div');head.append(el('h3',r.company||'Unknown'),el('p',(r.role||'Role not recorded')+' · '+(r.location||'Location not recorded')));c.append(head,pill(r),actions(r,bin));box.append(c)}return box}
function addField(dl,name,value){if(value===undefined||value===null||value==='')return;dl.append(el('dt',name));const dd=el('dd');dd.append(value instanceof Node?value:el('span',value));dl.append(dd)}
function section(root,title,value){if(!value)return;const s=el('section',undefined,'detail-section');s.append(el('h3',title),el('p',Array.isArray(value)?value.join('\n• '):value));root.append(s)}
function openDetail(r){const root=$('detail-body');root.replaceChildren(el('h2',r.company||'Unknown','detail-company'),el('p',r.role||'Role not recorded','detail-role'));root.append(pill(r));const dl=el('dl',undefined,'detail-grid');for(const [n,v] of [['Location',r.location],['Contact',r.recipient_name||r.contact_email],['Responsibility',r.recipient_role],['Applied on',r.applied_date],['Route',r.application_method||r.application_route],['Sent',r.sent_at&&fmt(r.sent_at)],['Gmail ID',r.gmail_message_id||r.message_id],['Checked',r.checked_at&&fmt(r.checked_at)],['Added by',r.contributor_name]])addField(dl,n,v);if(r.job_url)addField(dl,'Listing',link('Open listing',r.job_url));if(r.company_url)addField(dl,'Company',link('Company website',r.company_url));root.append(dl);section(root,'Why this role',r.fit);section(root,'Points to clarify',r.gaps);section(root,'Notes or outcome',r.notes||r.reason);section(root,'Email record',r.email_body);if(r.match_score?.rationale)section(root,'Match evidence',r.match_score.rationale);const docs=r.attachments||[];if(docs.length){const s=el('section',undefined,'detail-section');s.append(el('h3','Documents'));for(const d of docs){const b=el('button',d.filename||'Document','small-button');b.onclick=()=>downloadDocument(d);s.append(b,' ')}root.append(s)}const a=el('div',undefined,'detail-actions');if(!r.deleted){if(['ready','leads'].includes(group(r))){const b=el('button','Applied','primary');b.onclick=()=>{$('detail').close();openEditor(r,true)};a.append(b)}const b=el('button','Edit');b.onclick=()=>{$('detail').close();openEditor(r,false)};a.append(b)}else{const b=el('button','Restore');b.onclick=()=>{setDeleted(r,false);$('detail').close()};a.append(b)}root.append(a);$('detail').showModal()}
function route(r){if(r.application_route==='EMAIL')return 'Email';try{if(new URL(r.job_url).hostname.endsWith('seek.com'))return 'SEEK'}catch{}return r.job_url?'Company website':''}
function openEditor(r=null,apply=false){editing=r?.manual_entry_id?r:null;marking=r&&!editing?r:null;const f=$('record-form');f.reset();f.elements.status.querySelector('[data-current]')?.remove();$('editor-error').textContent='';const source=r||{};for(const k of ['company','role','location','job_url','contact_email','notes','contributor_name','applied_date','application_method'])if(f.elements[k])f.elements[k].value=source[k]||'';if(r?.status&&!Array.from(f.elements.status.options).some(o=>o.value===r.status)){const option=el('option','Current: '+label(r));option.value=r.status;option.dataset.current='true';f.elements.status.append(option)}f.elements.status.value=apply?'MANUAL_APPLIED':r?.status||'LEAD';if(apply){f.elements.contributor_name.value='Jeremie';f.elements.application_method.value=route(r);f.elements.applied_date.value=new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Sydney',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}$('editor-heading').textContent=apply?'MARK AS APPLIED':r?'EDIT RECORD':'NEW RECORD';$('editor').showModal()}
async function uploadDocument(file,id,kind){if(file.size>MAX_FILE)throw Error(file.name+' exceeds 10 MB.');if(!/\.(pdf|docx|png|jpe?g)$/i.test(file.name))throw Error('Use PDF, DOCX, PNG or JPG files.');const bytes=await file.arrayBuffer(),content=bytesToBase64(new Uint8Array(bytes));const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');return {filename:file.name,data_base64:content,sha256:hash,size_bytes:file.size,kind,uploaded_at:new Date().toISOString(),stored_in:'browser_export'}}
async function downloadDocument(d){if(d.unavailable){message('This upload has metadata only; its bytes were not available in the old export.',true);return}try{let bytes;if(d.data_base64)bytes=base64ToBytes(d.data_base64);else{const path=String(d.path||'').replace(/^\/?(?:dist\/)?/,'');if(!/^documents\/[^/]+$/.test(path))throw Error('Document path is unavailable.');const response=await fetch('./'+path);if(!response.ok)throw Error('Published document is missing.');bytes=new Uint8Array(await response.arrayBuffer())}const url=URL.createObjectURL(new Blob([bytes]));const a=el('a');a.href=url;a.download=d.filename||'document';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){message(e.message,true)}}
async function setDeleted(r,deleted){const key=r.key;const old=tracker.record_visibility.find(v=>v.record_key===key);if(old){old.deleted=deleted?1:0;old.version=(old.version||0)+1;old.updated_at=new Date().toISOString()}else tracker.record_visibility.push({record_key:key,deleted:deleted?1:0,version:1,updated_at:new Date().toISOString()});try{await save((deleted?'Move to Bin: ':'Restore: ')+r.company+' — '+r.role);message(deleted?'Moved to Bin.':'Restored.')}catch(e){await load();message(e.message,true)}}
$('record-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;const values=Object.fromEntries(new FormData(f));if(values.status==='MANUAL_APPLIED'&&(!values.applied_date||!values.application_method)){$('editor-error').textContent='Enter the actual application date and route.';return}const button=$('save');button.disabled=true;const id=editing?.id||crypto.randomUUID();let record=editing||{...(marking||{}),id,key:'manual:'+id,origin_key:marking?.key||null,created_at:new Date().toISOString(),attachments:[...(marking?.attachments||[])]};const old={...record},prior=tracker.manual_entries.findIndex(v=>v.id===id);Object.assign(record,Object.fromEntries(['company','role','location','job_url','status','applied_date','application_method','contact_email','notes','contributor_name'].map(k=>[k,values[k]||''])));record.updated_at=new Date().toISOString();record.version=(record.version||0)+1;if(prior<0)tracker.manual_entries.push(record);else tracker.manual_entries[prior]=record;let recorded=false;try{await save('Save tracker record: '+record.company+' — '+record.role);recorded=true;editing=record;marking=null;for(const kind of ['resume','cover','confirmation']){const file=f.elements[kind].files[0];if(!file)continue;message('Application recorded. Uploading '+file.name+'…');const doc=await uploadDocument(file,id,kind);record.attachments.push(doc);await save('Attach '+kind+' to '+record.company);f.elements[kind].value=''}$('editor').close();editing=null;message(record.status==='MANUAL_APPLIED'?'Saved in Applications. This did not submit the job application.':'Record saved.')}catch(error){if(!recorded){if(prior<0)tracker.manual_entries=tracker.manual_entries.filter(v=>v.id!==id);else tracker.manual_entries[prior]=old;try{await load()}catch{}}$('editor-error').textContent=(recorded?'The record was saved; an attachment needs another attempt. ':'')+error.message+' The form remains open.';message(error.message,true)}finally{button.disabled=false}});
$('unlock-form').addEventListener('submit',async e=>{e.preventDefault();const h=await sha256($('code').value);if(h!==CODE_HASH){$('unlock-error').textContent='Code not recognised.';return}$('code').value='';try{await load();$('unlock').hidden=true;$('workspace').hidden=false}catch(error){$('unlock-error').textContent=error.message}});
$('disconnect').onclick=()=>{$('workspace').hidden=true;$('unlock').hidden=false;$('code').focus()};
for(const id of ['all','applied','bin'])$('nav-'+id).onclick=()=>{tab=id;render()};
for(const id of ['table','scroll'])$(id+'-mode').onclick=()=>{mode=id;render()};
$('search').oninput=e=>{query=e.target.value;Object.keys(pages).forEach(k=>pages[k]=1);render()};
$('reload').onclick=async()=>{try{await load()}catch(e){message(e.message,true)}};
$('add').onclick=()=>openEditor();
$('confirm-delete').onclick=async()=>{if(!deleting)return;$('confirm').close();await setDeleted(deleting,true);deleting=null};
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
$('export').onclick=()=>{if(!tracker)return;const url=URL.createObjectURL(new Blob([JSON.stringify(tracker,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download='tracker-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('import').onclick=()=>$('import-file').click();
$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const incoming=JSON.parse(await file.text());validate(incoming);if(!confirm('Import this JSON into this browser? Existing local edits will take priority for matching records.'))return;tracker=mergeSnapshot(incoming,tracker);await save();message('Imported into this browser. Export JSON to share this version.')}catch(error){message('Import failed: '+error.message,true)}finally{e.target.value=''}};
