'use strict';
const $=id=>document.getElementById(id);
const CODE_HASH='49af5997d4acc06604f42debd0de05ed251efa294180ef06683555f79fd8b6bc';
const PAGE_SIZE=6,MAX_FILE=10*1024*1024;
let tracker=null,tab='all',mode='table',query='',editing=null,marking=null,deleting=null,publishedDigest=null,checkingPublished=false,cloudVersion=null,accessCode='';
const apiBase=String(window.TRACKER_API_URL||'').replace(/\/$/,'');
const cloudMode=!!apiBase;
const pages={},groups=[['applications','Applications'],['ready','Ready'],['leads','Leads'],['interviews','Interviews'],['offers','Offers'],['unsuccessful','Unsuccessful'],['attention','Needs attention']];
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n};
const fmt=v=>{if(!v)return 'Not recorded';const d=new Date(v);return Number.isNaN(d.valueOf())?String(v):new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Sydney',day:'numeric',month:'short',year:'numeric'}).format(d)};
const empty=()=>({applications:[],leads:[],manual_entries:[],record_visibility:[],deleted_keys:[],updated_at:new Date().toISOString()});
function message(s,warn=false){$('status').textContent=s;$('status').classList.toggle('warning',warn)}
function validUrl(u){try{const v=new URL(u);return ['https:','http:','mailto:'].includes(v.protocol)?v.href:null}catch{return null}}
function link(label,url){const a=el('a',label),safe=validUrl(url);if(!safe)return el('span',label);a.href=safe;a.target='_blank';a.rel='noopener noreferrer';return a}
function bytesToBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
function base64ToBytes(s){const raw=atob(s.replace(/\s/g,''));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function sha256(s){const h=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(h),v=>v.toString(16).padStart(2,'0')).join('')}
function openStore(){return new Promise((resolve,reject)=>{const req=indexedDB.open('marc-job-tracker',1);req.onupgradeneeded=()=>req.result.createObjectStore('records');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function readLocal(){const db=await openStore();return new Promise((resolve,reject)=>{const tx=db.transaction('records'),req=tx.objectStore('records').get('current');req.onsuccess=()=>{db.close();resolve(req.result||null)};req.onerror=()=>{db.close();reject(req.error)}})}
async function writeLocal(value){const db=await openStore();return new Promise((resolve,reject)=>{const tx=db.transaction('records','readwrite');tx.objectStore('records').put(value,'current');tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
function mergeSnapshot(base,local){
  if(!local)return base;
  const newer=(a,b)=>{const av=Number(a.version||0),bv=Number(b.version||0);if(av!==bv)return av>bv?a:b;return String(a.updated_at||'')>=String(b.updated_at||'')?a:b};
  for(const k of ['applications','leads']){const known=new Set(base[k].map(r=>r.key));for(const r of local[k]||[])if(!known.has(r.key))base[k].push(r)}
  const manual=new Map((base.manual_entries||[]).map(r=>[r.id,r]));
  for(const record of local.manual_entries||[]){
    const existing=manual.get(record.id);
    if(!existing){manual.set(record.id,record);continue}
    const merged={...newer(record,existing)},documents=new Map();
    for(const doc of [...(existing.attachments||[]),...(record.attachments||[])])documents.set(doc.id||doc.path||doc.sha256||doc.filename,doc);
    merged.attachments=[...documents.values()];manual.set(record.id,merged);
  }
  base.manual_entries=[...manual.values()];
  const visibility=new Map((base.record_visibility||[]).map(r=>[r.record_key,r]));for(const r of local.record_visibility||[])visibility.set(r.record_key,visibility.has(r.record_key)?newer(r,visibility.get(r.record_key)):r);
  base.record_visibility=[...visibility.values()];base.updated_at=String(local.updated_at||'')>String(base.updated_at||'')?local.updated_at:base.updated_at;return base;
}
async function fetchPublished(){const response=await fetch('./data.json?check='+Date.now(),{cache:'no-store'});if(!response.ok)throw Error('The published tracker data is unavailable.');const body=await response.text(),published=JSON.parse(body);validate(published);return {published,digest:await sha256(body)}}
async function cloudRequest(path,options={}){const response=await fetch(apiBase+path,{...options,cache:'no-store',headers:{'X-Tracker-Code':accessCode,...options.headers}});if(!response.ok){let reason;try{reason=(await response.json()).error}catch{}const exception=Error(reason||'Cloud service unavailable.');exception.status=response.status;throw exception}return response}
function syncDisplay(){
  $('sync-label').textContent=cloudMode?'CLOUD SAVE':'BROWSER SAVE';
  $('connection-label').textContent=cloudMode?'Shared cloud records':'Saved in this browser';
  $('sync-description').textContent=cloudMode?'Changes save to the shared Cloudflare database. Attachments are stored privately in R2.':'Cloud setup is pending. Edits on this page still stay on this device.';
  $('upload-hint').textContent=cloudMode?'Up to 10 MB each. New files are stored in Cloudflare R2.':'Up to 10 MB each. Cloud storage starts after setup.';
}
async function load(){
  message(cloudMode?'Checking shared records…':'Checking published records…');
  if(cloudMode){
    const response=await cloudRequest('/api/state');const body=await response.json();validate(body.state);
    tracker=body.state;cloudVersion=body.version;render();syncDisplay();
    const saved=await readLocal().catch(()=>null);
    $('legacy-export').hidden=!saved;
    message(saved?'Shared records loaded. Previous browser edits are still available as a separate backup; import them if needed.':'Shared cloud records loaded. Save is visible to everyone with the code.');
    return;
  }
  const {published,digest}=await fetchPublished();const saved=await readLocal();tracker=mergeSnapshot(published,saved);validate(tracker);publishedDigest=digest;render();syncDisplay();message(saved?'Published records checked. Browser edits remain local until cloud setup.':'Published tracker loaded. Save remains on this device until cloud setup.');
}
async function checkPublishedChanges(){if(checkingPublished||$('workspace').hidden||document.visibilityState==='hidden'||document.querySelector('dialog[open]'))return;checkingPublished=true;try{if(cloudMode){const response=await cloudRequest('/api/state');const body=await response.json();if(body.version!==cloudVersion){tracker=body.state;cloudVersion=body.version;render();message('New shared changes loaded.')}}else{const {digest}=await fetchPublished();if(digest!==publishedDigest){await load();message('New published records loaded. Browser edits remain local until cloud setup.')}}}catch(error){message(cloudMode?'Could not check cloud records. Save will not use a local fallback.':'Could not check the published copy. Your browser data is still here.',true)}finally{checkingPublished=false}}
function validate(d){if(!d||!Array.isArray(d.applications)||!Array.isArray(d.leads)||!Array.isArray(d.manual_entries)||!Array.isArray(d.record_visibility))throw Error('The private tracker JSON has an invalid format.')}
async function save(){
  tracker.updated_at=new Date().toISOString();
  if(cloudMode){
    if(!Number.isSafeInteger(cloudVersion))throw Error('The shared version is unavailable. Refresh before saving.');
    const response=await cloudRequest('/api/state',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_version:cloudVersion,state:tracker})});
    const result=await response.json();cloudVersion=result.version;tracker.updated_at=result.updated_at;
  }else await writeLocal(tracker);
  render();
}
function allRows(){const overrides=new Map(tracker.record_visibility.map(v=>[v.record_key,v]));const manual=tracker.manual_entries||[];const appliedKeys=new Set(manual.map(r=>r.origin_key).filter(Boolean));const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');const urlKey=s=>{try{const u=new URL(s);return u.hostname.toLowerCase()+u.pathname.replace(/\/$/,'').toLowerCase()}catch{return ''}};const urls=new Set(manual.map(r=>urlKey(r.job_url)).filter(Boolean)),names=new Set(manual.map(r=>norm(r.company)+'|'+norm(r.role))),seen=new Set();const automatic=[...tracker.applications,...tracker.leads].filter(r=>{if(seen.has(r.key))return false;seen.add(r.key);return overrides.get(r.key)?.deleted||(!appliedKeys.has(r.key)&&!(r.job_url&&urls.has(urlKey(r.job_url)))&&!names.has(norm(r.company)+'|'+norm(r.role)))});const rows=automatic.concat(manual.map(r=>({...r,key:r.key||'manual:'+r.id,manual_entry_id:r.id})));const active=[],bin=[];for(const r of rows){const vis=overrides.get(r.key);const record={...r,deleted:!!vis?.deleted,visibility_version:vis?.version||0};if(record.deleted)bin.push(record);else if(!/^EXPIRED$|^SKIPPED_EXPIRED$|^SKIPPED_CLOSED$|^VACANCY_REMOVED$/.test(record.status||''))active.push(record)}return {active,bin}}
function group(r){const s=r.status||'';if(s==='INTERVIEW')return 'interviews';if(s==='OFFER')return 'offers';if(s==='REJECTED')return 'unsuccessful';if(/^(SENT|EOI_SENT|MANUAL_APPLIED|MANUAL_APPLIED_SEEK_RECEIPT_CONFIRMED|APPLICATION_UNDER_REVIEW|DELIVERY_FAILED)$/.test(s))return 'applications';if(/BLOCKED|FAILED|UNCERTAIN|SENDING/.test(s))return 'attention';if(/READY|PREPARED|APPROVED/.test(s))return 'ready';return 'leads'}
function label(r){return ({SENT:'Email sent',EOI_SENT:'EOI sent',MANUAL_APPLIED:'Applied · reported',MANUAL_APPLIED_SEEK_RECEIPT_CONFIRMED:'Applied · receipt',APPLICATION_UNDER_REVIEW:'Under review',INTERVIEW:'Interview',OFFER:'Offer',REJECTED:'Unsuccessful',LEAD:'Lead',READY_FOR_JEREMIE:'Jeremie · apply',DELIVERY_FAILED:'Delivery failed',SEND_UNCERTAIN:'Send uncertain'})[r.status]||String(r.status||'Lead').replaceAll('_',' ').toLowerCase()}
function pill(r){const g=group(r);return el('span',label(r),'pill '+({applications:'applied',ready:'ready',interviews:'interview',attention:'attention'}[g]||''))}
function match(r){const v=r.match_score?.percent;if(typeof v!=='number')return null;const box=el('div',undefined,'match'+(v<80?' medium':'')),bar=el('div',undefined,'match-track'),fill=el('div',undefined,'match-fill');fill.style.width=Math.max(0,Math.min(100,v))+'%';bar.append(fill);box.append(el('span',v+'% fit'),bar);box.title='Judgement-based résumé or company-scope fit, not interview probability';return box}
function filtered(){const {active,bin}=allRows();const list=tab==='bin'?bin:tab==='applied'?active.filter(r=>group(r)==='applications'):active;const q=query.trim().toLowerCase();return q?list.filter(r=>[r.company,r.role,r.location,r.status].some(v=>String(v||'').toLowerCase().includes(q))):list}
function dayKey(value){if(/^\d{4}-\d{2}-\d{2}$/.test(String(value||'')))return value;const d=new Date(value);if(!value||Number.isNaN(d.valueOf()))return '';const parts=Object.fromEntries(new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Sydney',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d).map(p=>[p.type,p.value]));return `${parts.year}-${parts.month}-${parts.day}`}
function renderAnalytics(rows){
  const today=dayKey(new Date()),end=new Date(today+'T12:00:00Z'),days=[];
  for(let i=13;i>=0;i--){const d=new Date(end);d.setUTCDate(d.getUTCDate()-i*2);days.push({key:d.toISOString().slice(0,10),date:d,count:0})}
  const start=days[0].date.getTime();
  for(const r of rows){if(!/^(SENT|EOI_SENT|MANUAL_APPLIED|MANUAL_APPLIED_SEEK_RECEIPT_CONFIRMED|APPLICATION_UNDER_REVIEW)$/.test(r.status||''))continue;const date=dayKey(r.applied_date||r.sent_at),time=Date.parse(date+'T12:00:00Z');if(Number.isFinite(time)&&time>=start&&time<=end.getTime()){const bucket=Math.min(13,Math.floor((time-start)/(2*86400000)));days[bucket].count++}}
  const chart=$('activity-chart');chart.replaceChildren();const max=Math.max(1,...days.map(d=>d.count));
  const dateLabel=d=>new Intl.DateTimeFormat('en-AU',{day:'numeric',month:'short',timeZone:'UTC'}).format(d);
  for(const d of days){const column=el('div',undefined,'activity-column'),bar=el('span',undefined,'activity-bar');bar.style.setProperty('--bar-height',`${Math.max(d.count?11:3,d.count/max*100)}%`);column.title=`${dateLabel(d.date)}–${dateLabel(new Date(d.date.getTime()+86400000))}: ${d.count} application${d.count===1?'':'s'}`;column.setAttribute('aria-label',column.title);column.append(bar);chart.append(column)}
  const recentTotal=days.reduce((n,d)=>n+d.count,0);$('activity-total').replaceChildren(String(recentTotal)+' ',el('small','in 28 days'));chart.setAttribute('aria-label',`${recentTotal} recorded applications in the last 28 days; ${days.map(d=>`${dateLabel(d.date)}: ${d.count}`).join(', ')}`);
  $('activity-start').textContent=dateLabel(days[0].date);$('activity-end').textContent=dateLabel(end);$('overview-period').textContent=`${dateLabel(days[0].date).toUpperCase()} — ${dateLabel(end).toUpperCase()}`;
  const parts=[['applications','Applications','teal'],['ready','Ready','violet'],['leads','Research','blue'],['interviews','Interviews','amber'],['offers','Offers','green'],['unsuccessful','Unsuccessful','slate'],['attention','Attention','red']].map(([id,title,color])=>({id,title,color,count:rows.filter(r=>group(r)===id).length}));
  const bar=$('pipeline-chart'),legend=$('pipeline-legend');bar.replaceChildren();legend.replaceChildren();bar.setAttribute('aria-label',parts.map(p=>`${p.title}: ${p.count}`).join(', '));
  for(const p of parts){if(!p.count)continue;const segment=el('span',undefined,`pipeline-segment ${p.color}`);segment.style.flexGrow=p.count;segment.title=`${p.title}: ${p.count}`;bar.append(segment);const item=el('div',undefined,'legend-item');item.append(el('span',undefined,`legend-dot ${p.color}`),el('span',p.title),el('strong',p.count));legend.append(item)}
  if(!bar.childElementCount)bar.append(el('span','No active records','pipeline-empty'));
  const scores=rows.filter(r=>group(r)==='leads'&&Number.isFinite(r.match_score?.percent)).map(r=>r.match_score.percent),ranges=[['80–100%',scores.filter(v=>v>=80).length],['60–79%',scores.filter(v=>v>=60&&v<80).length],['Below 60%',scores.filter(v=>v<60).length]],fit=$('fit-chart');fit.replaceChildren();const highest=Math.max(1,...ranges.map(r=>r[1]));
  for(const [name,count] of ranges){const line=el('div',undefined,'fit-row'),track=el('span',undefined,'fit-track'),fill=el('span',undefined,'fit-bar');fill.style.width=`${count/highest*100}%`;track.append(fill);line.append(el('span',name),track,el('strong',count));fit.append(line)}
}
function render(){if(!tracker)return;const {active}=allRows();$('overview').hidden=tab!=='all';renderAnalytics(active);for(const [id,fn] of [['applications',r=>group(r)==='applications'],['ready',r=>group(r)==='ready'],['leads',r=>group(r)==='leads'],['interviews',r=>group(r)==='interviews']])$('count-'+id).textContent=active.filter(fn).length;$('updated').textContent='Last saved '+fmt(tracker.updated_at);$('page-title').textContent=tab==='bin'?'Bin':tab==='applied'?'Applications':'Applications and leads';$('section-name').textContent=tab==='bin'?'Bin':tab==='applied'?'Applications':'Overview';for(const id of ['all','applied','bin'])$('nav-'+id).classList.toggle('active',id===tab);$('table-mode').setAttribute('aria-pressed',String(mode==='table'));$('scroll-mode').setAttribute('aria-pressed',String(mode==='scroll'));const root=$('records');root.replaceChildren();const list=filtered();$('record-total').textContent=String(list.length).padStart(2,'0');if(tab==='bin'){root.append(renderCards(list,true));return}if(mode==='scroll'){root.append(renderCards(list,false));return}for(const [key,title] of groups){const subset=list.filter(r=>group(r)===key);if(!subset.length&&!['applications','ready','leads'].includes(key))continue;const section=el('section',undefined,'group'),h=el('h2',undefined,'group-title');h.append(title,el('span',subset.length));section.append(h);const wrap=el('div',undefined,'table-wrap');wrap.tabIndex=0;const table=el('table'),thead=el('thead'),thr=el('tr');for(const name of ['Company / role','Location','Contact','Status','Activity','Actions'])thr.append(el('th',name));thead.append(thr);table.append(thead);const body=el('tbody');const count=Math.max(1,Math.ceil(subset.length/PAGE_SIZE));pages[key]=Math.min(pages[key]||1,count);for(const r of subset.slice((pages[key]-1)*PAGE_SIZE,pages[key]*PAGE_SIZE))body.append(row(r));if(!subset.length){const tr=el('tr'),td=el('td','No '+title.toLowerCase()+' yet.','empty');td.colSpan=6;tr.append(td);body.append(tr)}table.append(body);wrap.append(table);section.append(wrap);if(count>1){const p=el('div',undefined,'pagination'),prev=el('button','Previous'),next=el('button','Next');prev.disabled=pages[key]===1;next.disabled=pages[key]===count;prev.onclick=()=>{pages[key]--;render()};next.onclick=()=>{pages[key]++;render()};p.append(prev,el('span',pages[key]+' / '+count),next);section.append(p)}root.append(section)}}
function actions(r,bin=false){const box=el('div',undefined,'row-actions'),details=el('button','Details');details.onclick=()=>openDetail(r);box.append(details);if(bin){const restore=el('button','Restore');restore.onclick=()=>setDeleted(r,false);box.append(restore)}else{if(['ready','leads'].includes(group(r))){const apply=el('button','Applied','applied-action');apply.onclick=()=>openEditor(r,true);box.append(apply)}const edit=el('button','Edit');edit.onclick=()=>openEditor(r,false);box.append(edit);const del=el('button','Delete');del.onclick=()=>{deleting=r;$('confirm-name').textContent=r.company+' — '+r.role;$('confirm').showModal()};box.append(del)}return box}
function row(r){const tr=el('tr'),co=el('td');co.append(el('strong',r.company||'Unknown'),el('small',r.role||'Role not recorded','role'));const m=match(r);if(m)co.append(m);tr.append(co,el('td',r.location||'Not recorded'),el('td',r.recipient_name||r.contact_email||'Contact needed'));const status=el('td');status.append(pill(r));tr.append(status,el('td',fmt(r.sent_at||r.checked_at||r.applied_date||r.updated_at)));const action=el('td');action.append(actions(r));tr.append(action);return tr}
function renderCards(list,bin){const box=el('div',undefined,'cards');if(!list.length)box.append(el('p',bin?'The Bin is empty.':'No matching records.','empty'));for(const r of list){const c=el('article',undefined,'card'),head=el('div');head.append(el('h3',r.company||'Unknown'),el('p',(r.role||'Role not recorded')+' · '+(r.location||'Location not recorded')));const m=match(r);if(m)head.append(m);c.append(head,pill(r),actions(r,bin));box.append(c)}return box}
function addField(dl,name,value){if(value===undefined||value===null||value==='')return;dl.append(el('dt',name));const dd=el('dd');dd.append(value instanceof Node?value:el('span',value));dl.append(dd)}
function section(root,title,value){if(!value)return;const s=el('section',undefined,'detail-section');s.append(el('h3',title),el('p',Array.isArray(value)?value.join('\n• '):value));root.append(s)}
function openDetail(r){const root=$('detail-body');root.replaceChildren(el('h2',r.company||'Unknown','detail-company'),el('p',r.role||'Role not recorded','detail-role'));root.append(pill(r));const dl=el('dl',undefined,'detail-grid');for(const [n,v] of [['Location',r.location],['Contact',r.recipient_name||r.contact_email],['Responsibility',r.recipient_role],['Applied on',r.applied_date],['Route',r.application_method||r.application_route],['Sent',r.sent_at&&fmt(r.sent_at)],['Gmail ID',r.gmail_message_id||r.message_id],['Checked',r.checked_at&&fmt(r.checked_at)],['Added by',r.contributor_name]])addField(dl,n,v);if(r.job_url)addField(dl,'Listing',link('Open listing',r.job_url));if(r.company_url)addField(dl,'Company',link('Company website',r.company_url));root.append(dl);section(root,'Why this role',r.fit);section(root,'Points to clarify',r.gaps);section(root,'Notes or outcome',r.notes||r.reason);section(root,'Email record',r.email_body);if(r.match_score?.rationale)section(root,'Match evidence',r.match_score.rationale);const docs=r.attachments||[];if(docs.length){const s=el('section',undefined,'detail-section');s.append(el('h3','Documents'));for(const d of docs){const b=el('button',d.filename||'Document','small-button');b.onclick=()=>downloadDocument(d);s.append(b,' ')}root.append(s)}const a=el('div',undefined,'detail-actions');if(!r.deleted){if(['ready','leads'].includes(group(r))){const b=el('button','Applied','primary');b.onclick=()=>{$('detail').close();openEditor(r,true)};a.append(b)}const b=el('button','Edit');b.onclick=()=>{$('detail').close();openEditor(r,false)};a.append(b)}else{const b=el('button','Restore');b.onclick=()=>{setDeleted(r,false);$('detail').close()};a.append(b)}root.append(a);$('detail').showModal()}
function route(r){if(r.application_route==='EMAIL')return 'Email';try{if(new URL(r.job_url).hostname.endsWith('seek.com'))return 'SEEK'}catch{}return r.job_url?'Company website':''}
function openEditor(r=null,apply=false){editing=r?.manual_entry_id?r:null;marking=r&&!editing?r:null;const f=$('record-form');f.reset();f.elements.status.querySelector('[data-current]')?.remove();$('editor-error').textContent='';const source=r||{};for(const k of ['company','role','location','job_url','contact_email','notes','contributor_name','applied_date','application_method'])if(f.elements[k])f.elements[k].value=source[k]||'';if(r?.status&&!Array.from(f.elements.status.options).some(o=>o.value===r.status)){const option=el('option','Current: '+label(r));option.value=r.status;option.dataset.current='true';f.elements.status.append(option)}f.elements.status.value=apply?'MANUAL_APPLIED':r?.status||'LEAD';if(apply){f.elements.contributor_name.value='Jeremie';f.elements.application_method.value=route(r);f.elements.applied_date.value=new Intl.DateTimeFormat('en-CA',{timeZone:'Australia/Sydney',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}$('editor-heading').textContent=apply?'MARK AS APPLIED':r?'EDIT RECORD':'NEW RECORD';$('editor').showModal()}
async function uploadDocument(file,id,kind){if(file.size>MAX_FILE)throw Error(file.name+' exceeds 10 MB.');if(!/\.(pdf|docx|png|jpe?g)$/i.test(file.name))throw Error('Use PDF, DOCX, PNG or JPG files.');if(cloudMode){const response=await cloudRequest('/api/documents',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(file.name),'X-Doc-Kind':kind},body:file});return response.json()}const bytes=await file.arrayBuffer(),content=bytesToBase64(new Uint8Array(bytes));const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');return {filename:file.name,data_base64:content,sha256:hash,size_bytes:file.size,kind,uploaded_at:new Date().toISOString(),stored_in:'browser_export'}}
async function downloadDocument(d){if(d.unavailable){message('This upload has metadata only; its bytes were not available in the old export.',true);return}try{let bytes;if(d.stored_in==='cloudflare_r2'&&cloudMode){const response=await cloudRequest(d.path);bytes=new Uint8Array(await response.arrayBuffer())}else if(d.data_base64)bytes=base64ToBytes(d.data_base64);else{const path=String(d.path||'').replace(/^\/?(?:dist\/)?/,'');if(!/^documents\/[^/]+$/.test(path))throw Error('Document path is unavailable.');const response=await fetch('./'+path);if(!response.ok)throw Error('Published document is missing.');bytes=new Uint8Array(await response.arrayBuffer())}const url=URL.createObjectURL(new Blob([bytes]));const a=el('a');a.href=url;a.download=d.filename||'document';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){message(e.message,true)}}
async function setDeleted(r,deleted){const key=r.key;const old=tracker.record_visibility.find(v=>v.record_key===key);if(old){old.deleted=deleted?1:0;old.version=(old.version||0)+1;old.updated_at=new Date().toISOString()}else tracker.record_visibility.push({record_key:key,deleted:deleted?1:0,version:1,updated_at:new Date().toISOString()});try{await save();message(deleted?(cloudMode?'Moved to the shared Bin.':'Moved to Bin in this browser. Cloud setup is pending.'):(cloudMode?'Restored for everyone.':'Restored in this browser. Cloud setup is pending.'))}catch(e){await load().catch(()=>{});message(e.message,true)}}
$('record-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;if(!f.reportValidity())return;const values=Object.fromEntries(new FormData(f));if(values.status==='MANUAL_APPLIED'&&(!values.applied_date||!values.application_method)){$('editor-error').textContent='Enter the actual application date and route.';return}const button=$('save');button.disabled=true;const id=editing?.id||crypto.randomUUID();let record=editing||{...(marking||{}),id,key:'manual:'+id,origin_key:marking?.key||null,created_at:new Date().toISOString(),attachments:[...(marking?.attachments||[])]};const old={...record},prior=tracker.manual_entries.findIndex(v=>v.id===id);Object.assign(record,Object.fromEntries(['company','role','location','job_url','status','applied_date','application_method','contact_email','notes','contributor_name'].map(k=>[k,values[k]||''])));record.updated_at=new Date().toISOString();record.version=(record.version||0)+1;if(prior<0)tracker.manual_entries.push(record);else tracker.manual_entries[prior]=record;let recorded=false;try{await save();recorded=true;editing=record;marking=null;for(const kind of ['resume','cover','confirmation']){const file=f.elements[kind].files[0];if(!file)continue;message('Record saved. Uploading '+file.name+'…');const doc=await uploadDocument(file,id,kind);f.elements[kind].value='';record.attachments.push(doc);await save()}$('editor').close();editing=null;message(record.status==='MANUAL_APPLIED'?(cloudMode?'Saved in shared Applications. This did not submit the job application.':'Saved in Applications on this browser. Cloud setup is pending; this did not submit the job application.'):(cloudMode?'Saved to the shared tracker.':'Saved on this browser. Cloud setup is pending.'))}catch(error){if(!recorded){if(prior<0)tracker.manual_entries=tracker.manual_entries.filter(v=>v.id!==id);else tracker.manual_entries[prior]=old;try{await load();const existing=tracker.manual_entries.find(v=>v.id===id);if(existing){recorded=true;editing=existing;marking=null}}catch{}}else if(error.status===409){const pending=[...(record.attachments||[])];try{await load();const latest=tracker.manual_entries.find(v=>v.id===id);if(latest){const known=new Set((latest.attachments||[]).map(d=>d.id||d.sha256));for(const doc of pending)if(!known.has(doc.id||doc.sha256))latest.attachments.push(doc);editing=latest;record=latest}}catch{}}$('editor-error').textContent=(recorded?'The record exists; review any attachment and save again. ':'')+error.message+' The form remains open.';message(error.message,true)}finally{button.disabled=false}});
$('unlock-form').addEventListener('submit',async e=>{e.preventDefault();const code=$('code').value,h=await sha256(code);if(h!==CODE_HASH){$('unlock-error').textContent='Code not recognised.';return}accessCode=code;$('code').value='';try{await load();$('unlock').hidden=true;$('workspace').hidden=false}catch(error){accessCode='';$('unlock-error').textContent=error.message}});
$('disconnect').onclick=()=>{accessCode='';tracker=null;cloudVersion=null;$('workspace').hidden=true;$('unlock').hidden=false;$('code').focus()};
for(const id of ['all','applied','bin'])$('nav-'+id).onclick=()=>{tab=id;render()};
for(const id of ['table','scroll'])$(id+'-mode').onclick=()=>{mode=id;render()};
$('search').oninput=e=>{query=e.target.value;Object.keys(pages).forEach(k=>pages[k]=1);render()};
$('reload').onclick=async()=>{try{await load()}catch(e){message(e.message,true)}};
$('add').onclick=()=>openEditor();
$('confirm-delete').onclick=async()=>{if(!deleting)return;$('confirm').close();await setDeleted(deleting,true);deleting=null};
for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
function exportJson(value,prefix='tracker-backup'){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=el('a');a.href=url;a.download=prefix+'-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('export').onclick=()=>{if(tracker)exportJson(tracker)};
$('legacy-export').onclick=async()=>{const previous=await readLocal();if(previous)exportJson(previous,'previous-browser-edits')};
$('import').onclick=()=>$('import-file').click();
async function migrateInlineAttachments(state){for(const record of state.manual_entries){for(let i=0;i<(record.attachments||[]).length;i++){const doc=record.attachments[i];if(!doc.data_base64)continue;const bytes=base64ToBytes(doc.data_base64);if(bytes.byteLength>MAX_FILE)throw Error('An imported attachment exceeds 10 MB.');const file=new File([bytes],doc.filename||'document.pdf');const uploaded=await uploadDocument(file,record.id,doc.kind||'confirmation');if(doc.sha256&&doc.sha256!==uploaded.sha256)throw Error('Imported attachment checksum mismatch.');record.attachments[i]={...doc,...uploaded,data_base64:undefined}}}}
$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const incoming=JSON.parse(await file.text());validate(incoming);if(!confirm(cloudMode?'Merge this backup into the shared cloud tracker? Existing records and newer versions will be retained.':'Import this JSON into this browser? Existing local edits will take priority for matching records.'))return;const merged=mergeSnapshot(structuredClone(tracker),incoming);if(cloudMode){if(JSON.stringify(merged.applications)!==JSON.stringify(tracker.applications)||JSON.stringify(merged.leads)!==JSON.stringify(tracker.leads))throw Error('This backup changes automatic history. Reconcile those records before importing.');await migrateInlineAttachments(merged)}tracker=merged;await save();message(cloudMode?'Backup merged into the shared tracker.':'Imported into this browser. Cloud setup is pending.')}catch(error){if(cloudMode)await load().catch(()=>{});message('Import failed: '+error.message,true)}finally{e.target.value=''}};

setInterval(checkPublishedChanges,60000);window.addEventListener('focus',checkPublishedChanges);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkPublishedChanges()});
